<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LearningJournalSelfSeeder extends Seeder
{
    public function run()
    {
       DB::table('learning_journal_self')->insert([
    [
        'learning_journal_id' => 1,
        'my_lesson' => 'Vocabulary in IT English',
        'time_allocation' => '6 hours',
        'learning_resources' => 'Online articles, vocabulary lists',
        'learning_activities' => 'Reading, note-taking, vocabulary quizzes',
        'isConcentration' => true,
        'isFollowPlan' => true,
        'evaluation' => 'Focused and achieved my goals',
        'reinforcing' => 'Review words daily, use them in writing',
        'note' => 'Need more technical writing practice',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'learning_journal_id' => 2,
        'my_lesson' => 'TOEIC listening drills',
        'time_allocation' => '4 hours',
        'learning_resources' => 'TOEIC practice app, audio recordings',
        'learning_activities' => 'Listening tests, vocabulary matching',
        'isConcentration' => false,
        'isFollowPlan' => true,
        'evaluation' => 'Missed focus midweek',
        'reinforcing' => 'Change study time to early morning',
        'note' => 'Audio too fast, repeat sessions needed',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'learning_journal_id' => 3,
        'my_lesson' => 'Speaking practice: introductions & small talk',
        'time_allocation' => '5 hours',
        'learning_resources' => 'YouTube speaking tips, peer practice',
        'learning_activities' => 'Pair conversations, role-play',
        'isConcentration' => true,
        'isFollowPlan' => false,
        'evaluation' => 'Spoke well but didn’t review feedback',
        'reinforcing' => 'Record self and analyze',
        'note' => 'Next week: focus on feedback usage',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'learning_journal_id' => 4,
        'my_lesson' => 'English phrasal verbs',
        'time_allocation' => '3 hours',
        'learning_resources' => 'Quizlet, textbooks',
        'learning_activities' => 'Flashcards, sentence writing',
        'isConcentration' => false,
        'isFollowPlan' => false,
        'evaluation' => 'Easily distracted, inconsistent',
        'reinforcing' => 'Shorter focused sessions',
        'note' => 'Stick to 30-minute sessions with breaks',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'learning_journal_id' => 5,
        'my_lesson' => 'Business communication in English',
        'time_allocation' => '6 hours',
        'learning_resources' => 'Lecture slides, email samples',
        'learning_activities' => 'Writing emails, peer review',
        'isConcentration' => true,
        'isFollowPlan' => true,
        'evaluation' => 'Productive and on schedule',
        'reinforcing' => 'Keep routine and add mock meetings',
        'note' => 'Start drafting LinkedIn profile',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    // Tuần 2
    [
        'learning_journal_id' => 6,
        'my_lesson' => 'Technical reading in IT',
        'time_allocation' => '5 hours',
        'learning_resources' => 'IT blogs, documentation',
        'learning_activities' => 'Skimming, summarizing',
        'isConcentration' => true,
        'isFollowPlan' => true,
        'evaluation' => 'Efficient reading, good retention',
        'reinforcing' => 'Summarize daily readings',
        'note' => 'Practice writing summaries',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'learning_journal_id' => 7,
        'my_lesson' => 'TOEIC reading and vocabulary',
        'time_allocation' => '4.5 hours',
        'learning_resources' => 'TOEIC textbook, vocabulary app',
        'learning_activities' => 'Practice tests, review mistakes',
        'isConcentration' => true,
        'isFollowPlan' => true,
        'evaluation' => 'Completed all planned activities',
        'reinforcing' => 'Repeat incorrect questions daily',
        'note' => 'Need faster scanning skills',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'learning_journal_id' => 8,
        'my_lesson' => 'Speaking: expressing opinions',
        'time_allocation' => '5 hours',
        'learning_resources' => 'Speaking prompt cards, friends',
        'learning_activities' => 'Timed responses, debates',
        'isConcentration' => true,
        'isFollowPlan' => false,
        'evaluation' => 'Spoke confidently but off-topic',
        'reinforcing' => 'Practice with clear structure',
        'note' => 'Focus more on coherence',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'learning_journal_id' => 9,
        'my_lesson' => 'Idioms and expressions',
        'time_allocation' => '3.5 hours',
        'learning_resources' => 'Idiom dictionary, example videos',
        'learning_activities' => 'Flashcards, dialogues',
        'isConcentration' => false,
        'isFollowPlan' => true,
        'evaluation' => 'Learned many idioms but forgot quickly',
        'reinforcing' => 'Use idioms in speaking practice',
        'note' => 'Review before bed daily',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'learning_journal_id' => 10,
        'my_lesson' => 'TOEIC speaking practice',
        'time_allocation' => '6 hours',
        'learning_resources' => 'Simulated speaking tests',
        'learning_activities' => 'Answer recording, feedback analysis',
        'isConcentration' => true,
        'isFollowPlan' => true,
        'evaluation' => 'Spoke more clearly and confidently',
        'reinforcing' => 'Continue feedback sessions',
        'note' => 'Next: focus on spontaneous answers',
        'created_at' => now(),
        'updated_at' => now(),
    ],
]);
    }
}
